### ISSUE TITLE
대충 로고를 만들어 봤어요

### ISSUE THREAD

**Issue by beewee22** [megazone-devops/maryo#17]
<img width="116" alt="maryo-logo" src="https://user-images.githubusercontent.com/14936270/64090189-e69df700-cd84-11e9-85f5-f6ca9e3fd1bd.png">

어떤 것 같나요?? 편하게 의견 주세요!

**Comment by pio500** [comment]
저런 느낌으로 사각형으로 하면 어떨까요? 두겹으로 하니까 저희가 만들고 있는 yml 시가고하 한 모양이랑 비슷하게 보이기도 할 것 같아서요!

**Comment by beewee22** [comment]
아는 디자이너한테 수정을 맡겨볼게요!
